version: "3.8"
services:
  # UI/UX
  front:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    environment:
      - NODE_ENV=development
    container_name: react-package-starter
